{{- if .Values.backend.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ .Values.namespace }}"
  name: {{ .Values.backend.secrets.name  }}
data:
  {{- range $key, $val := .Values.backend.secrets.data }}
  {{ $key }}: {{ $val | quote  }}
  {{- end}}
type: Opaque
{{- end }}