apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.tls_backend_crt }}
  tls.key: {{ .Values.ingress.tls_backend_key }}
kind: Secret
metadata:
  name: {{ .Values.ingress.tls_backend_secret_name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls