apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: "{{ .Values.namespace }}"
  {{- with .Values.backend.deployment_labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.backendConfig.backend.name }}"}'
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- with .Values.backend.deployment_labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}